package residuosquimicos

public enum LaboratorioList {
    //CB - Departamento de Antibióticos
    LABORATORIO_DE_FARMACOLOGIA_E_CANCEROLOGIA_EXPERIMENTAIS("Lab. de Farmacologia e Cancerologia Experimentais (Toxologia e Cancerologia Experimental)"),
    LABORATORIO_DE_CULTURA_DE_CELULAS_DEPARTAMENTO_DE_ANTIBIOTICOS("Lab. de Cultura de Células"),
    BIOFARMATOX_SALA_1("Laboratório de Prospecção Farmacotoxicológica de Produtos Bioativos - BIOFARMATOX - sala 1"),
    BIOFARMATOX_SALA_2("Laboratório de Prospecção Farmacotoxicológica de Produtos Bioativos - BIOFARMATOX - sala 2"),
    LAMAI("Laboratório de Microbiologial Industrial e Ambiental - LAMAI"),
    LEA("Laboratório de Etnofarmacologia Aplicada - LEA"),
    LABORATORIO_DE_BIOPROCESSOS_E_BIOPRODUTOS("Laboratório de Bioprocessos e Bioprodutos"),
    LABORATORIO_DE_AULAS_PRATICAS("Laboratório de Aulas Práticas"),
    LABORATORIO_DE_MEIO_DE_CULTURA("Laboratório de Meio de Cultura"),
    LABORATORIO_DE_MICROBIOLOGIA_APLICADA_E_ENSAIOS_ANTIMICROBIANOS("Laboratório de Microbiologia Aplicada e Ensaios Antimicrobianos"),
    LABORATORIO_DE_GENETICA_DE_MICRORGANISMOS("Laboratório de Genética de microrganismos"),
    COLECAO_DE_MICROORGANISMOS_UFPEDA("Coleção de Microorganimos - UFPEDA"),
    LABORATORIO_DE_PROCESSOS_BIOTECNOLOGICOS_DA("Laboratório de Processos Biotecnológicos"),
    LABORATORIO_DE_FISIOLOGIA_DE_BIOQUIMICA_DE_MICRORGANISMO("Laboratório de Fisiologia e Bioquímica de Microrganismo"),
    LQIT("Laboratório de Química e Inovação Terapêutica - LQIT"),
    LABORATORIO_DE_QUIMICA_DE_PRODUTOS_NATURAIS_DA("Laboratório de Química de Produtos Naturais"),
    LABORATORIO_DE_SINTESE_E_QUIMICA_DE_PRODUTOS_NATURAIS("Laboratório de Síntese e Química de Produtos Naturais"),
    LABORATORIO_DE_SINTESE_DE_SUBSTANCIAS_DE_INTERESSE_TERAPEUTICO("Lab.  de Síntese de Substâncias de Interesse Terapêutico"),
    LABORATORIO_DE_PRODUTOS_NATURAIS_E_SINTETICOS("Laboratório de Produtos Naturais e sintéticos"),

    //Departamento de Anatomia Humana
    LABORATORIO_DE_ANATOMIA_E("Laboratório de Anatomia E"),
    SALA_DE_DISSECACAO_2("Sala de Dissecação 2"),
    LABORATORIO_DE_ANATOMIA_D("Laboratório de Anatomia D"),
    LABORATORIO_DE_ANATOMIA_A("Laboratório de Anatomia A"),
    LABORATORIO_DE_ANATOMIA_B("Laboratório de Anatomia B"),
    LABORATORIO_DE_ANATOMIA_C("Laboratório de Anatomia C"),
    LABORATORIO_DE_DISSECACAO_1("Sala de Dissecação 1"),
    LABORATORIO_DE_HISTOQUIMICA("Laboratório de Histoquímica"),
    LABORATORIO_DE_PERFUSAO("Laboratório de Perfusão"),
    LABORATORIO_DE_EXTEROTAXIA("Laboratório de Exterotaxia"),
    BIOTERIO_ANATOMIA("Biotério"),

    //Departamento de Biofísica  Radiologia
    LABORATORIO_DE_RADIOLOGIA("Laboratório de Radiobiologia"),
    LABORATORIO_DE_BIOFISICA_QUIMICA("Laboratório de Biofísica Química"),
    LBCM("Laboratório de Biofísica Celular Molecular- LBCM"),
    BIOFISICA_DAS_MEMBRANAS_E_CELULAS_DR_OLEG_KRASILNIKOV("Biofísica das Membranas e Células Tronco- Dr.Oleg Krasilnikov"),
    ENEGNHARIA_BIOMEDICA("Engenharia Biomédica"),

    //Departamento de Bioquímica
    LABORATORIO_DE_BIOTECNOLOGIA_BIOQUIMICA("Laboratório de Biotecnologia"),
    BIOTERIO_BIOQUIMICA("Biotério"),
    LABORATORIO_DE_ENZIMOLOGIA("Laboratório de Enzimologia"),
    BIOPROT_1("Laboratório de Bioquímica de proteínas (BIOPROT 1)"),
    BIOPROT_2("Laboratório de Bioquímica de proteínas (BIOPROT 2)"),
    LAB_DE_LIPIDIOS_METABOLISTMO_DE_LIPITIODS_E_LIPOPROTEINAS("Lab.  de Lipídios, Metabolismo de Lipídios e Lipoproteínas"),
    LABORATORIO_DE_QUIMICA_DE_PRODUTOS_NATURAIS("Laboratório de Química de Produtos Naturais"),
    LABORATORIO_DE_ENGENHARIA_METABOLICA("Laboratório de Engenharia Metabólica"),
    BIONANO("Laboratório de Bionanotecnologia (BIONANO)"),
    LABORATORIO_DE_BIOLOGIA_MOLECULAR_DB("Laboratório de Biologia Molecular"),
    SALAS_DE_AULAS_PRATICAS_BIOFISICA("Salas de Aulas Práticas - Biofísica"),
    SALAS_DE_AULAS_PRATICAS_BIOQUIMICA("Salas de Aulas Práticas - Bioquímica"),

    //Departamento de Botânica

    LEVA("Laboratório de Ecologia Vegetal Aplicada (LEVA)"),
    LEAF("Laboratório de Ecologia Aplicada e Fitoquímica (LEAF)"),
    LABORATORIO_DE_INTERACOES_MULTITROFICAS("Laboratório de Interações Multitróficas"),
    LIPA("Laboratório de Interação Planta-Animal (LIPA)"),
    LABORATORIO_DIDATICO_DE_MORFOLOGIA_E_FISIOLOGIA_VEGETAL("Laboratório Didático de Morfologia e Fisiologia Vegetal"),
    LABORATORIO_DE_ECOFISIOLOGIA_VEGETAL("Laboratório de Ecofisiologia Vegetal"),
    LABORATORIO_DE_SISTEMATICA_DE_FANEROGAMOS("Laboratório Sistemática de Fanerógamos"),
    POLINIZAR("Laboratório de Biologia Floral e reprodutiva- POLINIZAR"),
    LABORATORIO_DE_MORFOTAXONOMIA_VEGETAL("Laboratório de Morfotaxonomia Vegetal"),
    LABORATORIO_DE_CITOGENETICA_E_EVOLUCAO_VEGETAL("Laboratório de Citogenética e Evolução Vegetal"),
    LABORATORIO_DE_BIOLOGIA_DE_BRIOFITAS("Laboratório de Biologia de Briófitas"),
    LABORATORIO_DE_ECOLOGIA_APLICADA("Laboratório de Ecologia Aplicada"),
    LABORATORIO_DE_PTERIDOFITAS("Laboratório de Pteridófitas"),
    LABORATORIO_DE_MIXOMICETOS("Laboratório de Mixomicetos"),
    LABORATORIO_DE_ANATOMIA_VEGETAL("Laboratório de Anatomia Vegetal"),

    //Departamento de Fisiologia e Farmacologia
    LABORATORIO_DE_REATIVIDADE_VASCULAR("Laboratório de Reatividade Vascular"),
    LABORATORIO_DE_NEUROFISIOLOGIA_1("Laboratório de Neurofisiologia 1"),
    BIOTERIO_FISIOLOGIA_I("Biotério I"),
    BIOTERIO_FISIOLOGIA_II("Biotério II"),
    LABORATORIO_DE_FISIOLOGIA_CARDIOPULMONAR("Laboratório  de Fisiologia Cardiopulmonar"),
    LABORATORIO_DE_ENDOCRINOLOGIA_E_METABOLISMO("Laboratório de Endocrinologia e Metabolismo"),
    LABORATORIO_DE_PANCREAS_ENDOCRINO("Laboratório de Pâncreas Endócrino"),
    LABORATORIO_DE_FARMACOLOGIA_CARDIOVASCULAR("Laboratório de Farmacologia Cardiovascular"),
    LABORATORIO_DE_FISIOLOGIA_COMPARADA("Laboratório de Fisiologia Comparada"),
    LABORATORIO_DE_NEUROENDOCRINOLOGIA_E_METABOLISTMO_1("Laboratório de Neuroendocrinologia e Metabolismo 1"),
    LABORATORIO_DE_NEUROENDOCRINOLOGIA_E_METABOLISTMO_2("Laboratório de Neuroendocrinologia e Metabolismo 2"),
    SALA_MEZANINO("Sala Mezanino (aulas)"),
    LABORATORIO_DE_FARMACOLOGIA_RENAL("Laboratório de Farmacologia Renal"),
    LABORATORIO_DE_FARMACOLOGIA_E_TOXICOLOGIA_PRE_CLINICA("Laboratório de Farmacologia e Toxicologia Pré-Clínica"),
    LABORATORIO_DE_PRODUTOS_BIOATIVOS("Laboratório de Produtos Bioativos"),
    LABORATORIO_DE_NEUROFARMACOLOGIA("Laboratório de Neurofarmacologia"),
    LABORATORIO_DE_NEUROFISIOLOGIA_2("Laboratório de Neurofisiologia 2"),

    //Departamento de Genética
    LABORATORIO_DE_GENETICA_E_BIOTECNOLOGIA_VEGETAL("Laboratório de Genética e Biotecnologia Vegetal"),
    DINE("Laboratório de Genoma e Proteônica (DINE)"),
    LABORATORIO_DE_GENETICA_E_CITOGENETICA_ANIMAL_E_HUMANA("Laboratório de Genética e Citogenética Animal e Humana"),
    LABORATORIO_DE_GENETICA_MOLECULAR("Laboratório de Genética Molecular"),
    LABORATORIO_DE_GENETICA_MICROORGANISMOS("Laboratório de Genética Microorganismos"),
    LED("Laboratório de Experimentação em Drosophila ( LED)"),
    LABORATORIO_DE_GENETICA_MOLECULAR_HUMANA("Laboratório de Genética Molecular Humana"),
    LABORATORIO_DE_BIO_INFORMATICA_E_BILOGIA_EVOLUTIVA("Laboratório de Bio-informática e Biologia Evolutiva"),

    //Departamento de Histologia e Embriologia

    LABORATORIO_DE_CULTURA_DE_CELULAS("Laboratório de Cultura de Células"),

    //Departamento de Micologia

    LABORATORIO_DE_POS_GRADUACAO_EM_BIOLOGIA_DE_FUNGOS_1("Laboratório de Pós-graduação em Biologia de Fungos 1"),
    LABORATORIO_DE_POS_GRADUACAO_EM_BIOLOGIA_DE_FUNGOS_2("Laboratório de Pós-graduação em Biologia de Fungos 2"),
    LABORATORIO_DE_MICOLOGIA_MEDICA_HUMANA_E_VETERINARIA("Laboratório de Micologia Médica humana e Veterinária"),
    LABORATORIO_DE_BIOLOGIA_MOLECULAR_DE_FUNGOS("Laboratório  de Biologia Molecular de Fungos"),
    PGBP_2("Laboratório de Taxonomia  e Sistemática de Fungos (PGBP 2)"),
    LABORATORIO_DE_CITOLOGIA_E_GENETICA("Laboratório de Micologia Ambiental ( Lab. Citologia e Genética)"),
    LABORATORIO_DE_HIFOMICETOS("Laboratório de Hifomicetos"),
    LABORATORIO_DE_MICORRIZAS("Laboratório de Micorrizas"),
    LABORATORIO_DE_TAXONOMIA_BIOTECNOLOGIA("Departamento de Taxonomia Biotecnologia"),
    IMUNODIAGNOSTICO_DE_MICOSES_SISTEMICAS("Imunodiagnóstico de Micoses Sistêmicas"),
    LABORATORIO_DE_FUNGOS_FITOPATOGENICOS("Laboratório de Fungos Fitopatogênicos"),
    MICOTECA("Micoteca"),
    MEIO_DE_CULTURA("Meio de Cultura"),
    HERBARIO_MICOLOGIA("Herbário"),

    //Departamento de Zoologia
    LABORATORIO_DE_AQUICULTURA("Laboratório de Aqüicultura"),
    ARREAGUA("Laboratório de Avaliação, Recuperação e Restauração de Ecossistemas – ARREAGUA"),
    LACMAR("Laboratório de Comunidades Marinhas - LACMAR"),
    LAEBRY("Laboratório de Estudos de Bryozoa - LAEBRY"),
    LABORATORIO_DE_ETNOECOLOGIA_E_EDUCACAO_AMBIENTAL("Laboratório de Etnoecologia e Educação Ambiental"),
    LABORATORIO_DE_ETOLOGIA("Laboratório de Etologia"),
    LAPTX("Laboratório de Toxinas e Herpetologia (Animais Peçonhentos e Toxinas - LAPTX)"),
    LABORATORIO_DE_BIOLOGIA_DE_CONSERVACAO("Laboratório de Biologia de Conservação"),
    LABORATORIO_DE_BIOLOGIA_DE_CRUSTACEOS("Laboratório de Biologia de Crustáceos"),
    LABORATORIO_DE_CIENCIAS_APLICADAS_A_CONSERVACAO_DA_BIODIVERSIDADE("Laboratório de Ciências Aplicada à Conservação da Biodiversidade"),
    LACIMME("Laboratório de Cultivo de Meiofauna Marinha e Estuarina – LACIMME"),
    LABDIN("Laboratório de Dinâmica de Populações - LABDIN"),
    LABORATORIO_DE_ECOTOXICOLOGIA_AQUATICA("Laboratório de Ecotoxicologia Aquática"),
    LABORATORIO_DE_ENTOMOLOGIA_APLICADA("Laboratório de Entomologia Aplicada (Insetário)"),
    LABORATORIO_DE_ETOMOLOGIA_FORENSE("Laboratório de Entomologia Forense (Insetos Necrófagos)"),
    LABORATORIO_DE_GENOMICA_EVOLUTIVA_E_AMBIENTAL("Laboratório de Genômica Evolutiva e Ambiental (Biotecnologia)"),
    LIT("Laboratório de Invertebrados Terrestres (LIT)"),
    LABORATORIO_DE_MASTOZOOLOGIA("Laboratório de Mastozoologia"),
    LABORATORIO_DE_MEIOFAUNA("Laboratório de Meiofauna"),
    LABORATORIO_DE_ORNITOLOGIA("Laboratório de Ornitologia"),
    LABPOR("Laboratório de Porifera - LABPOR"),
    LABORATORIO_DE_TAXONOMIA_E_ECOLOGIA_DE_INSETOS("Laboratório de Taxonomia e Ecologia de Insetos"),
    LABORATORIO_DE_10("Laboratório 10 (para aulas)"),
    LABORATORIO_DE_07("Laboratório 07 (para aulas)"),

    //Laboratório Central - CB

    HERBARIO_LABORATORIO_CENTRAL("Herbário"),
    LABORATORIO_DE_GENOMICA_E_EXPRESSAO_GENICA("Laboratório de Genômica e expressão Gênica"),
    SALA_DE_COLETAS_GINECOLOGICAS("Sala de Coletas Ginecológicas"),
    LABORATORIO_DE_COLETAS_SANGUE("Laboratório de Coletas (Sangue)"),
    LEMTE("Laboratório de Estudos Moleculares e Terapia Experimental (LEMTE)"),
    LABORATORIO_DE_HEMATOLOGIA_LABORATORIO_CENTRAL("Laboratório de Hematologia"),
    LABORATORIO_DE_BIOTECNOLOGIA_LC("Laboratório de Biotecnologia"),
    LABORATORIO_DE_BIOTECNOLOGIA_ANEXO("Laboratório de Biotecnologia (Anexo)"),
    LABORATORIO_DE_BIOQUIMICA_CLINICA_PARASITOLOGIA_E_URINALISES("Laboratório de Bioquímica Clínica (Parasitologia e Urinálises)"),
    LABORATORIO_DE_CULTURA_DE_CELULAS_LABORATORIO_CENTRAL("Laboratório de Cultura de Células"),
    LABORATORIO_MOLECULAR("Laboratório Molecular"),
    LABORATORIO_DE_CITOLOGIA_CLINICA_CB("Laboratório de Citologia Clínica"),

    //---------------------------------
    //LABORATORIOS CCS

    //Departamento de Ciências Farmacêuticas
    NCOMC("Núcleo de Controle de Qualidade de Medicamentos Correlatos (NCQMC)"),
    NUDFAC("Núcleo de Desenvolvimento Farmacêutico e Cosmético (NUDFAC)"),
    LAPETOX("Laboratório de Toxicologia (LAPETOX)"),
    UAC("Laboratório de Análise Clínica (UAC)"),
    LABORATORIO_DE_MICROBIOLOGIA_CLINICA("Laboratório de Microbiologia Clínica"),
    LABSINFA("Laboratório de Planejamento Avaliação e Síntese de Fármacos (LABSINFA)"),
    FARMACOGNOSIA_I_E_II("Farmacognosia I e II"),
    LABORATORIO_DE_FARMACEUTICA("Laboratório de Química Farmacêutica"),
    LAPRONAT("Laboratório de Produtos Naturais (LAPRONAT)"),
    LABORATORIO_DE_INFORMATICA_DCF("Laboratório de Informática"),
    LABORATORIO_DE_PRODUTOS_HOMOTERAPICOS("Laboratório de Produtos Homoterápicos"),
    LABORATORIO_DE_CITOLOGIA_CLINICA_CCS("Laboratório de Citologia Clínica"),
    LABORATORIO_DE_COSMETICOS_E_SANIFICANTES("Laboratório de Cosméticos e Sanificantes"),
    FARMACIA_ESCOLA("Farmácia Escola"),
    LQTM("Laboratório de Química Teórica Medicinal (LQTM)"),
    LABORATORIO_DE_FARMACOTECNICA_I_II("Laboratório de Farmacotécnica I e II (NUDFAC)"),
    LABORATORIO_DE_PESQUISA_DCF("Laboratório de Pesquisa"),
    LABORATORIO_DE_IMUNOLOGIA_CLINICA("Laboratório de Imunologia Clínica"),
    BIOTERIO_DEPARTAMENTO_DE_CIENCIAS_FARMACEUTICAS("Biotério"),
    CENTRO_DE_PESQUISA_DESENVOLVIMENTO_E_INOVACAO("Centro de Pesquisa, Desenvolvimento e Inovação (PD&I) (NUDFAC)"),
    LABORATORIO_DE_ANALISE_MICROBIOLOGICA("Laboratório de Análise Microbiológica"),
    LPQM("Laboratório de Planejamento em Química Medicinal (LPQM)"),
    LABORATORIO_DE_TECNOLOGIA_DE_MEDICAMENTOS("Laboratório de Tecnologia  de Medicamentos"),
    LABORATORIO_DE_CONTROLE_MICROBIOLOGICO("Laboratório de Controle Microbiológico"),
    LABORATORIO_DE_SINTESE_ORGANICA_APLICADA_E_FARMACOS("Laboratório de Síntese Orgânica Aplicada a Fármacos"),
    LABORATORIO_DE_BIOTECNOLOGIA_E_PRODUCAO_DE_HEMODERIVADOS("Laboratório de Biotecnologia e Produção de Hemoderivados"),
    LABORATORIO_DE_BIOQUIMICA_CLINICA("Laboratório de Bioquímica Clínica"),

    //Departamento de Cirurgia
    MODULO_DE_CIRURGIA_ABDOMINAL("Módulo de cirurgia abdominal, introdução a clínica e a técnica cirúrgica"),
    MODULO_DE_CIRURGIA_UROLOGIA_E_VASCULAR("Módulo de cirurgia, urologia e vascular"),
    MODULO_DE_CIRURGIA_TRAUMATOLOGICA("Módulo de cirurgia traumatológica"),
    MODULO_DE_CIRURGIA_TRAUMATOLOGICA_ORTOPEDISTA("Módulo de cirurgia traumatológica/ortopedia"),
    MODULO_DE_CIRURGIA_PEDIATRICA("Módulo de cirurgia pediátrica"),
    MODULO_DE_CIRURGIA_OFTAMOLOGICA("Módulo de cirurgia oftamológica"),
    MODULO_DE_CIRURGIA_OTORRINOLOGICA("Módulo de cirurgia Otorrinológica"),
    MODULO_DE_CIRURGIA_CIRURGIA_VASCULAR("Módulo de cirurgia vascular"),
    NUCLEO_DE_CIRURGIA_EXPERIMENTAL("Núcleo de Cirurgia Experimental"),

    //Departamento  de Clínica Odontologica Preventiva
    CLINICA_CEO("Clínica CEO"),
    ABORATORIO_DE_ORTONDOTIA("Laboratório de Ortondotia"),
    CLINICA_INTEGRAL("Clínica Integral"),
    CLINICA_DE_ODONTOLOGIA_PREVENTIVA("Clínica de Odontologia Preventiva"),
    ABORATORIO_DE_ESTOMATOLOGIA("Laboratório de Estomatologia"),
    ABORATORIO_DE_RADIOLOGIA("Laboratório de Radiologia"),
    PERIONDOTIA("Periodontia"),
    PATOLOGIA_DCOP("Patologia"),

    //Departamento de Enfermagem
    LABORATORIO_DE_ENFERMAGEM("Laboratório de Enfermagem"),

    //Departamento de Fisioterapia
    LABORATORIO_DE_FISIOTERAPIA_CARDIO_RESPIRATORIO("Laboratório de Fisioterapia Cardio Respiratório"),
    LABORATORIO_DE_RECURSOS_TERAPEUTICO_ANUAIS("Laboratório de Recursos Terapêutico anuais"),
    LABORATORIO_DE_CINESOLOGIA("Laboratório de Cinesologia"),
    LABORATORIO_DE_ELETROTERMOFOTOTERAPIA("Laboratório de Eletrotermofototerapia"),

    //Departamento de Fonodiaulogia
    CLINICA_DE_FONODIAULOGICA("Clinica de Fonodiaulogia (3 Laboratórios)"),

    //Departamento de Medicina Tropical
    LABORATORIO_DE_AULAS_PRATICAS_8("Laboratório  de aulas práticas 8"),
    LABORATORIO_DE_AULAS_PRATICAS_7("Laboratório  de aulas práticas 7"),
    LABORATORIO_DE_MEIOS_DE_CULTIVO("Laboratório de Meios de Cultivo"),
    LABORATORIO_DE_ESTERELIZACAO("Laboratório de Esterelização"),
    LABORATORIO_DE_BIOFILMES("Laboratório de Biofilmes"),
    LABORATORIO_DE_GENETICA_BACTERIANA("Laboratório de Genética Bacteriana"),
    LABORATORIO_DE_BACTERIOLOGIA("Laboratório de Bacteriologia"),
    CORREDOR("Corredor"),
    MOLUSCARIO("Moluscário"),
    LABORATORIO_DE_PROCESSAMENTO_DE_AMOSTRAS("Laboratório Processamento de amostras"),
    SALA_DE_CULTURA("Sala de Cultura"),
    LABORATORIO_DE_PESQUISAS_DE_OPORTUNISTAS("Laboratório de Pesquisas de oportunistas"),
    SALA_DE_METODOS("Sala de Métodos"),

   // Departamento de Nutrição
    LNC("Laboratório de Nutrição Clínica (LNC)"),
    LEAAL("Laboratório de Experimentação  e Análise de Alimentos (LEAAL)"),
    LEAAL_FISICO_QUIMICA("LEAAL - Laboratório de Físico-Química"),
    LEAAL_MICROSCOPIA("LEAAL - Laboratório de Microscopia"),
    LEAAL_MUTIUSUARIO("LEAAL - Laboratório Multiusuário"),
    LEAAL_MICROBIOLOGIA_BACTERIAS("LEAAL - Laboratório de Microbiologia (Bactérias)"),
    LEAAL_MICROBIOLOGIA_FUNGOS("LEAAL - Laboratório  de Microbiologia (Fungos)"),
    LAB_DE_ESTUDOS_EM_NUTRICAO_E_INSTRUMENTACAO_BIOMEDICA("Lab. de Estudos em Nutrição e Instrumentação Biomédica"),
    LAB_DE_ESTUDOS_EM_NUTRICAO_E_INSTRUMENTACAO_BIOMEDICA_3_BIOTERIOS("Lab. de Estudos em Nutrição e Instrumentação Biomédica ( 3 BIOTÉRIOS)"),
    LNED("Laboratório de Nurtrição Experimental e Dietética (LNED)"),
    LNED_BIOTERIO("Laboratório de Nurtrição Experimental e Dietética (LNED) -  BIOTÉRIO"),
    BIOTERIO_NUTRICAO("Biotério ( 3 unidades)"),
    SALA_DE_SACRIFICIOS_NUTRICAO("Sala de Sacrifícios"),
    LNSP("Laboratório de Nutrição em Saúde Pública (LNSP)"),
    LBQN_1("Laboratório de Bioquímica da Nutrição 1 (LBQN)"),
    LBQN_2("Laboratório de Bioquímica da Nutrição 2 (LBQN)"),
    LAFINNT("Laboratório de Fisiologia da Nutrição Naide Teodósio (LAFINNT)"),


    //Departamento de Patologia
    LABORATORIO_DE_PATOLOGIA_MOLECULAR("Laboratório de Patologia Molecular"),
    LABORATORIO_DE_PATOLOGIA_POS("Laboratório de Patologia (Pós-Graduação)"),
    MUSEU_PATOLOGIA("Museu"),
    HD_PATOLOGIA("Laboratório de Patologia (HC)"),
    LIKA_PATOLOGIA("Laboratório de Patologia (LIKA)"),

    //Departamento de Prótese e Cirurgia Bucofacial
    LABORATORIO_DE_DENTISTA_E_MATERIAIS_DENTARIOS("Laboratórios de Dentista e Materiais Dentários"),
    BLOCO_CIRURGICO("Bloco Cirurgico"),
    CLINICA_INTEGRADA_E_CIRURGICA("Clinica Integrada e Cirúrgica"),
    LABORATORIO_DE_DENTISTA_2_3_ENDODONTIA("Laboratório de Dentista 2 e 3 e Endodontia"),
    NAPA("Núcleo de Pronto Atendimento (NAPA)"),
    CLINICA_DE_PROTESES("Clinica de Próteses"),
    AMBULATORIO_DE_TRAUMATOLOGIA("Ambulatório de Traumatologia (Lab. de Cirurgia e Traumatologia Buco-Maxilo-Facial)"),

    //-----------------------
    //LABORATORIOS CTG
    // Departamento de Engenharia Cartográfica
    LAGEO("Laboratório de Astronomia e Geodésia (LAGEO)"),
    LACAD("Laboratório de Cadastro e Gestão Territorial (LACAD)"),
    LACCOST("Laboratório de Cartografia Costeira (LACCOST)"),
    LAFOTO("Laboratório de Fotogrametria (LAFOTO)"),
    LAINFO("Laboratório de Informática (LAINFO)"),
    LAMEPE("Laboratório de Metrologia e Posicionamento Espacial (LAMEPE)"),
    LAPROC("Laboratório de Processamento de Imagens (LAPROC)"),
    LASENSO("Laboratório de Sensoriamento Remoto (LASENSO)"),
    LATEGEO("Laboratório de Tecnologias da Geoinformação (LATECGEO)"),
    LATOP("Laboratório de Topografia (LATOP)"),

    //Departamento de Engenharia Civil
    LABORATORIO_DE_HIDRAULICA_APLICADA("Laboratório de Hidráulica Aplicada"),
    LSA("Laboratório de Saneamento Ambiental (LSA)"),
    GEOPROCESSAMENTO_E_RECURSOS_HIDRICOS("Geoprocessamento e Recursos Hídricos"),
    HIDROLOGIA("Hidrologia"),
    SOLOS_E_INSTRUMENTACAO("Solos e Instrumentação"),
    LABORATORIO_DE_COMPUTACAO_DE_ALTO_DESEMPENHO("Laboratório de Computação de Alto Desempenho"),
    LABORATORIO_DE_MATERIAIS_E_ESTRUTURAS("Laboratório de Materiais e Estruturas"),
    LABORATORIO_DE_TRANSPORTES("Laboratório de Transportes"),

    //Departamento de Engenharia Mecânica
    LABORATORIO_DE_USINAGEM("Laboratório de Usinagem"),
    LABORATORIO_DE_METALOGRAFIA_E_CARACTERIZACAO_MICROESTRUTURAL("Laboratório de Metalografia e Caracterização Microestrutural"),
    LABORATORIO_DE_FUSAO_E_TRANSFORMACAO_DE_FASE("Laboratório de Fusão e Transformação de Fase"),
    LEDEX("Laboratório de Difração e Espalhamento de Raios-X - LEDEX"),
    LABORATORIO_DE_ENSAIOS_MECANICOS("Laboratório de Ensaios Mecânicos"),
    AREA_DE_TESTES_DE_TURBINAS_EOLICAS("Área de Testes de Turbinas Eólicas"),
    AREA_DE_TESTES_DE_SISTEMAS_HIBRIDOS_EOLICO_SOLAR_BATERIA("Área de Testes de Sistemas Híbridos - Eólico/Solar/Bateria"),
    TURBINA_EOLICA_DE_FERNANDO_DE_NORONHA("Turbina Eólica de Fernando de Noronha"),
    LABTERMO_I("Sistemas e Processos Térmicos, (LABTERMO I)"),
    LABTERMO_II("Refrigeração e Conforto Ambiental, (LABTERMO II)"),
    LABTERMO_III("Área de Teste de Motores, (LABTERMO III)"),
    LABTERMO_IV("Simulação Numérica e Desenvolvimento de Software, (LABTERMO IV)"),
    LES_UFPE("Laboratório de Energia Solar, (LES/UFPE)"),
    LABCOM("Laboratório de Computação para Mecânica Computacional - LABCOM"),
    FADLAB("Laboratório de Computação de Alto Desempenho - PADLAB"),
    LABEND("Laboratório de Ensaios Não-destrutivos - LABEND"),
    LABGESSO("Laboratório de Tecnologia do Gesso - LABGESSO"),
    LDP_FLU("Laboratório Didático-pedagógico de Fluidos - LDP-FLU"),

    //Departamento de Engenharia Química
    LABORATORIO_DE_ANALISE_INSTRUMENTAL("Laboratório de Análise Instrumental"),
    LABORATORIO_DE_ELETROQUIMICA_CORROSAO("Laboratório de Eletroquímica/Corrosão"),
    LABORATORIO_DE_ENGENHARIA_QUIMICA("Laboratório de Engenharia Química"),
    LABORATORIO_DE_MICROBIOLOGIA("Laboratório de Microbiologia"),
    LABORATORIO_DE_ORGANICA("Laboratório de Orgânica"),
    LABORATORIO_DE_QUIMICA_ANALITICA("Laboratório de Química Analítica"),
    LABORATORIO_DE_QUIMICA_INORGANICA("Laboratório de Química Inorgânica"),
    LABORATORIO_DE_HIALOTCNIA("Laboratório de Hialotcnia"),
    LABORATORIO_DE_ANALISES_MINERAIS_SOLOS_E_AGUAS("Laboratório de Análises Minerais Solos e Água"),
    LABORATORIO_DE_COMBUSTIVEL("Laboratório de Combustível"),
    LABORATORIO_DE_CONTROLE_DE_QUALIDADE("Laboratório de Controle de Qualidade"),
    LABORATORIO_DE_CROMATOGRAFIA_INSTRUMENTAL("Laboratório de Cromatografia Instrumental"),
    LABORATORIO_DE_ENGENHARIA_AMBIENTAL_E_DA_QUALIDADE("Laboratório de Engenharia Ambiental e da Qualidade"),
    LABORATORIO_DE_MATERIAIS_POLIMERICOS_E_CARACTERIZACAO("Laboratório de Materiais Poliméricos e Caracterização"),
    LABORATORIO_DE_MICROBIOLOGIA_AMBIENTAL("Laboratório de Microbiologia Ambiental"),
    LABORATORIO_DE_MICROBIOLOGIA_INDUSTRIAL("Laboratório de Microbiologia Industrial"),
    LABORATORIO_DE_PROCESSOS_BIOTECNOLOGICOS_EQ("Laboratório de Processos Biotecnológicos"),
    LABORATORIO_DE_PROCESSO_CATALITICOS("Laboratório  de Processo Catalíticos"),
    LABORATORIO_DE_PROCESSOS_E_TECNOLOGIA_AMBIENTAIS("Laboratório de Processos  e Tecnológia Ambientais"),
    LABORATORIO_DE_PROCESSOS_QUIMICOS("Laboratório de Processos Químicos"),
    LABORATORIO_DE_TECNOLOGIAS_LIMPAS("Laboratório de Tecnologias Limpas"),
    LABORATORIO_DE_CONTROLE_E_OTIMIZACAO_DE_PROCESSOS("Laboratório  de Controle e Otimização de Processos"),

    //Departamento de Engenharia de Produção
    LABORATORIO_DE_PLANEJAMENTO_E_GESTAO_DE_RECURSOS_HIDRICOS("Laboratório de Planejamento e Gestão de Recursos Hídricos"),
    LABORATORIO_DE_RISCOS_TECNOLOGICOS("Laboratório de Riscos Tecnológicos"),

    //Departamento de Eletrônicos e Sistemas
    LABORATORIO_DE_ENGENHARIA_BIOMEDICA("Laboratório de Engenharia Biomédica"),

    //Departamento de Engenharia de Minas
    LABORATORIO_DE_QUIMICA_INTERFACE("Laboratório de Química interface"),
    LABORATORIO_DE_METALURGIA_EXTRATIVA("Laboratório de Metalurgia Extrativa"),
    LABORATORIO_DE_COMUNICACAO("Laboratório de Comunuição"),
    LAPLA("Laboratório de Planejamento de Lavra - LAPLA"),
    LABORATORIO_DE_CONTROLE_AMBIENTAL_DE_MINERACAO("Laboratório de Controle Ambiental de Mineração"),
    LAB_DE_ENSINO_E_PESQUISA_EM_AUTOMACAO_NA_MINERACAO("Lab.  de Ensino e Pesquisa em Automoção na Mineração"),

    //Departamento de Energia Nuclear
    LABORATORIO_DE_MICROBIOLOGIA_DE_SOLO("Laboratório de Microbiologia de Solo"),
    LABORATORIO_DE_FERTILIDADE_DE_SOLOS("Laboratório de Fertilidade de Solos"),
    LABORATORIO_DE_FISICA_DE_SOLOS("Laboratório de Física de Solos"),
    LABORATORIO_DE_PROTECAO_RADIOLOGICA("Laboratório de Proteção Radiológica"),
    LABORATORIO_DE_DOSIMETRIA_AMBIENTAL("Laboratório de Dosimetria Ambiental"),
    LAMBDA("Laboratório de Modelagem e Bisiometria Aplicada (LAMBDA)"),
    LABORATORIO_DE_METROLOGIA_DAS_RADIACOES_LONIZONTES("Laboratório de Metrologia das Radiações Lonizontes"),
    LABORATORIO_DE_RADIOQUIMICA("Laboratório de Radioquímica"),


    //Departamento de Oceanografia
    LOQUIM("Laboratório de Oceanografia Química (LOQUIM)"),
    LABORATORIO_DE_FITOPLANCTON("Laboratório de Fitoplâncton"),
    LABORATORIO_DE_ZOOPLANCTION("Laboratório de Zooplâncton"),
    LABORATORIO_DE_BENTOS_I("Laboratório de Bentos"),
    LABORATORIO_DE_BENTOS_II("Laboratório de Bentos II"),
    LABORATORIO_DE_NECTON("Laboratório de Necton"),
    LOFEC("Lab. de Física Marinha  Física Esturiana e Costeira (LOFEC)"),
    LABORATORIO_DE_OCEONAGRAFIA_GEOLOGICA("Laboratório de Oceanografia Geológica"),
    ORGANOMAR("Lab. Composto de Orgânicos em Ecossistema Costeiros e Marinhos (OrganoMAR)"),
    LABOGEO("Laboratório de Carcinologia  (LABOGEO)"),
    LACE("Laboratório de Cultivo e Ecotoxocologia (LACE)"),
    LEGECE("Lab. de Ecologia e Gerenciamento de Ecossistemas Costeiros e Estuarino (LEGECE)"),
    LABORATORIO_DE_HIDRODINAMICA_COSTEIRA("Laboratório de Hidrodinâmica Costeira"),
    LABORATORIO_DE_APOIO_MULTIUSUARIO("Laboratório de Apoio Multiusuário"),

    // Departamento de Geologia
    LABORATORIO_DE_SISMOESTRATIGRAFIA("Laboratório de Sismoestratigrafia"),
    LABORATORIO_DE_CATODOLUMINESCENCIA("Laboratório de Catodoluminescência"),
    LGA("Laboratório de Geofísica Aplicada (LGA)"),
    LABORATORIO_DE_GEOFISICA_PROF_HELMO_HAND("Laboratório de Geogísica Prof.º Helmo Hand"),
    GGM("Laboratório de Geologia e Geofísica Marinha (GGM)"),
    LEGESE("Laboratório de Geologia Sedimentar e Ambiental (LEGESE)"),
    LABORATORIO_DE_GEOQUIMICA("Laboratório de Geoquímica"),
    LABHID("Laboratório de Hodrogeologia (LABHID)"),
    LABORATORIO_DO_ICP("Laboratório do ICP"),
    LABORATORIO_DE_INCLUSOES_FLUIDAS("Laboratório de Inclusões Fluídas"),
    LAFIR("Laboratório de Índices Físicos de Rochas (LAFIR)"),
    LABORATORIO_DE_MICROSCOPIA_OPTICA("Laboratório de Microscopia Óptica"),
    MEV_WSD("Lab. de Microscopia  Eletrônica de Varredura (MEV-WSD)"),
    LABORATORIO_DE_PALEONTOLOGIA_DO_DGEO("Laboratório de Paleontologia do DGEO"),
    LABORATORIO_DE_PREPARACAO_DE_AMOSTRAS_E_LAMINACAO("Laboratório de Preparação de Amostras e Laminação"),
    LABORATORIO_DE_ANALISES_SEDIMENTOLOGICAS("Laboratório de Análises Sedimentológicas"),
    NEG_LABSE("Núcleo de Estudos Geoquímicos- Laboratório de Isotopos Estáveis (NEG-LABISE)"),


    //Departamento de Física
    ATOMOS_FRIOS("Átomos Frios"),
    DINAMICA_LASER("Dinâmica Laser"),
    ESPALHAMENTO_DE_LUZ_BRILLOUIN("Espalhamento de Luz Brillouin"),
    ESPECTROSCOPIA_ATOMICA_LASER_PULSADO("Espectroscopia Atômica / Laser Pulsado"),
    OTICA_E_FISICA_ATOMICA("Ótica e Física Atômica"),
    FENOMENOS_ULTRA_RAPIDOS_1("Fenômenos Ultra-Rápidos 1"),
    FOTONICA_E_BIOFOTONICA("Fotônica e Biofotônica"),
    IMAGEAMENTO_POR_RESSONANCIA_MAGNETICA_NUCLEAR("Imageamento por Ressonância Magnética Nuclear"),
    MAGNETOMETRIA("Magnetometria"),
    MAGNETOMETRIA_CAMPOS_INTENSO("Magnetometria - Campos Intenso"),
    MAGNOMETRIA_POR_SQUID("Magnetometria  Por Squid"),
    MAGNETO_OPTICA("Magneto-Óptica"),
    MICRO_ELETRONICA("Micro Eletrônica"),
    MICROSCOPIA_ELETRONICA_DE_VARREDURA("Microscopia Eletrônica de Varredura"),
    NANO_OPTICA("Nano Óptica"),
    OPTICA_NAO_LINEAR_E_OPTO_ELETRONICA("Óptica Não Linear e Opto Eletrônica"),
    POLIMETOS_NAO_CONVENCIONAIS("Polímeros Não Convencionais"),
    PREPARACAO_DE_MATERIAIAS_MAGNETICOS("Preparação de Materiais Magnéticos"),
    RAIO_X_LAB_MATERIAIS_AVANCADOS("Raio X  (Lab. Materiais Avançados)"),
    SUPERCONDUTIVIDADE_TECNICAS_REED("Supercondutividade- Tecnicas Reed"),
    SUPERCONDUTIVIDADE_PROP_DE_TRANSPORTE("Supercondutividade-Prop. De Transporte"),
    SUPERCONDUTIVIDADE_PROP_MAGNETICAS("Supercondutividade-Prop. Magnéticas"),
    SUPERCONDUTIVIDADE_SINTESE_DE_MATERIAIS("Supercondutividade-Síntese de Materiais"),
    TRANSPORTE_E_CALORIMETRIA("Transporte e Calorimetria"),
    ALMOXARIFADO("Almoxarifado"),
    CRIOGENIA("Criogenia"),
    ELETRONICA_OFICINA("Eletrônica (Oficina)"),
    FISICA_MODERNA_LABORATORIO("Física Moderna (Laboratório)"),
    INSTRUMENTACAO_P_O_ENSINO_MEDIO("InstrumentaÇão p o Ensino Médio"),
    MANUTENCAO_OFICINA("Manutenção (Oficina)"),
    MECANICA_OFICINA("Mecânica (oficina)"),
    OPTICA_MODERNA_LABORATORIO("Óptica Moderna (Laboratório)"),
    OTIRCA_OFICINA("Ótica (Oficina)"),
    PREPARACAO_DE_MATERIAIS("Preparação de Materiais"),
    PREPARACAO_PARA_O_ENSINO_MEDIO("Preparação para o Ensino Médio"),
    QUIMICA_LABORATORIO("Química (Laboratório)"),
    SALA_LIMPA("Sala Limpa"),
    SPUTTERING("Sputtering"),
    REDES_QUANTICAS("Redes quânticas"),
    ESTADOS_QUANTICOS_DA_LUZ("Estados quânticos da luz"),
    VSM("VSM"),
    RESSONANANCIA_FERROMAGNETICA("Ressonância Ferromagnética"),
    NANOFENTOLAB("Nanofentolab"),
    PULSOS_ULTRACURTOS_E_ULTRAVIOLETA_EXTERNO("Pulsos Ultracurtos e Ultravioleta externo"),
    LOGICA_QUANTICA("Lógica Quântica"),
    METROLOGICA_OPTICA("Metrologia Óptica"),
    BIOTERIO("Biotério"),
    RESSONANCIA_MAGNETICA_NUCLEAR("Ressonância Magnética Nuclear 1/2"),

    //Departamento de Química Fundamental
    CENTRAL_ANALITICA("Central Analítica"),
    IAAQ("Inst. Aut. p/ Anal. Quím. (IAAQ)"),
    COMPOSTOS_HIBRIDOS_INTERFACES("Compostos Híbridos Interfaces"),
    INSTRUMENTOS_P_ENSINO("Instrumento p/ Ensino"),
    OFICINA_DE_HIALOTECNIA("Oficina de Hialotecnia"),
    ECOLOGIA_QUIMICA("Ecologia Química"),
    LABORATORIO_RMN("Laboratório RMN"),
    LEEMM("LEEMM – Lab. Eletroquímica Edson Mororó Moura"),
    LMS("Metodologia e Síntese (LMS"),
    SINTESE_ORGANICA("Síntese Orgânica"),
    CATALISE_E_ORGANOMETALICOS("Catálise e Organometálicos"),
    ELETROANALITICA("Eletroanalítica"),
    ELETROSSINTESE_ORGANICA("Eletrossíntese Orgânica"),
    ORGANICA_AVANCADA("Orgânica Avançada"),
    MATERIAIS_VITRIOS_E_NANODISPOSITIVO_FOTONICO("Materiais Vítrios e Nanodispositivo  Fotônico"),
    PRODUTOS_NATURAIS("Produtos Naturais"),
    LAB_DE_BIOMATERIAIS("Lab. Biomateriais"),
    POLIMEROS("Polímeros"),
    TERRAS_RARAS("Terras Raras"),
    ORGANOMETALICOS("Organometálicos"),
    ARQUITETURA_MOLECULAR("Arquitetura Molecular"),
    LQTC_1("Química Computacional 1 – LQTC"),
    LQTC_2("Química Computacional 2 – LQTC"),
    QUIMICA_DE_ESTADO_SOLIDO("Química de Estado Sólido"),
    ESPECTROSCOPIA_BSTR_1("Espectroscopia BSTR 1"),
    ESPECTROSCOPIA_BSTR_2("Espectroscopia BSTR 2"),
    LABORATORIO_DE_ENSINO_1_E_2("Laboratórios de Ensino 1 e 2"),
    LABORATORIO_RMN_400_MHZ_CA("Laboratório RMN 400 MHZ (CA)"),

    //------------------

    //LABORATORIOS CE
    COLEGIO_DE_APLICACAO("Colégio de Aplicação"),
    LABORATORIO_DE_INFORMATICA_CE("Laboratório de Informática"),
    LABORATORIO_DE_QUIMICA("Laboratório de Química"),
    LABORATORIO_DE_MATEMATICA_FISICA("Laboratório de Matemática/Física"),
    LABORATORIO_DE_BIOLOGIA("Laboratório de Biologia"),

    //--------------------------
    //LABORATORIOS INDEPENDENTES
    DINE_POSITIVA("DINE Positiva"),
    COLEGIO_DE_GENOMA("Laboratório de Genoma"),
    NUCLEO_DE_PESQUISA_EM_INOVACAO_TERAPEUTICA("Núcleo de Pesquisa em Inovação Terapêutica"),

    //LIKA
    LABORATORIO_DE_IMUNOLOGIA("Laboratório de Imunologia"),
    LABORATORIO_DE_PATOLOGIA("Laboratório de Patologia"),
    LABORATORIO_DE_MICROSPIA_ELETRONICA("Laboratório de Microspia Eletrônica"),
    LABORATORIO_DE_BIOQUIMICA("Laboratório de Bioquímica"),
    LABORATORIO_DE_MICOLOGIA("Laboratório de Micologia"),
    LABORATORIO_DE_BIOLOGIA_MOLECULAR_LIKA("Laboratório de Biologia Molecular"),
    LABORATORIO_DE_VIROLOGIA("Laboratório de Virologia"),
    LABORATORIO_DE_BIOTECNOLOGIA_LIKA("Laboratório de Biotecnologia"),
    BIOTERIO_LIKA("Biotério"),
    NAI("NAI – Núcleo de Atendimento ao Idoso")


    public String value

    LaboratorioList(String value){
        this.value = value
    }

    String toString() { value }
    String getKey() { name() }
}